### ISSUE TITLE
the example is not working: 

### ISSUE THREAD

**Issue by himamura2** [chjackson/a2bcovid#1]
Hi Chris,
I am trying to run the example and I got the following error and I cannot see where this errors are coming from.
  
library('a2bcovid')
pat_file <- system.file("extdata", "Example_genetic_temporal_data.csv", package="a2bcovid")
 a <- a2bcovid(pat_file = pat_file)
Error reading NS threshold: File not found ../Data/Thresholds95NS.dat
Error reading NS threshold: File not found ../Data/Thresholds99NS.dat
Error reading thresholds.  Can't find file ../Data/Thresholds95.dat: Check this
Error reading thresholds.  Can't find file ../Data/Thresholds99.dat: Check this
Error in `$<-.data.frame`(`*tmp*`, "from", value = integer(0)) : 
  replacement has 0 rows, data has 1

Could you help me understand this?
best,
Hideo

**Comment by cjri** [comment]
Hi Chris,

The error arises because we have altered the code in such a way that the likelihood thresholds are dependent on the values D_A and D_B, the times at which sequences were collected.

The files Thresholds95NS.dat etc are included in the A2BCovid package on GitHub, and need to be located in the directory ../Data relative to the working directory.

Does the above make sense to you?

Thanks,

Chris

**Comment by chjackson** [comment]
@himamura2 It's not your fault - these files aren't in the repository.  We'll work on a fix and update you when it's done. 

@cjri The bug report wasn't from me, it was from a user.  I can't see these thresholds files anywhere in the repository.  Could you put them there, and I can help integrate them with the R version if need be?  Users shouldn't have to put them in place themselves - the example should just work.

**Comment by himamura2** [comment]
Thank you Chris/Chris for quick replies
>" can't see these thresholds files anywhere in the repository."
I looked for Thresholds95NS.dat or etc in R package folders and a2bcovid folders downloaded from github but I do not see them. Or I tried to see a string "Thresholds95", but I could not find.  I am looking forward to the updates. 
Hideo

**Comment by cjri** [comment]
Sorry, my fault.  I thought I had uploaded these alongside the other files.

Chris

**Comment by cjri** [comment]
Hi Chris,

I have uploaded the files now.  I had put a directory containing them in my a2bcovid folder and assumed they would update to GitHub, but apparently not.

Chris

**Comment by himamura2** [comment]
Thank you Chris,
I reinstalled by install_github("chjackson/a2bcovid"), and now I get data/ folder. I just renamed it to Data/. It seems this Data/ folder has to be always ../Data/ to cwd. 
so, just run it in Data

setwd("Data")
pat_file <- system.file("extdata", "Example_genetic_temporal_data.csv", package="a2bcovid")
a <- a2bcovid(pat_file = pat_file) # OK

Have complete data for 10 individuals
Find variants NoSeq
Calculate likelihoods
Default location parameters were used to assess transmission events involving some individuals:
CAMP001001
> setwd('..')
>  a <- a2bcovid(pat_file = pat_file) # Not OK
Error reading NS threshold: File not found ../Data/Thresholds95NS.dat
Error reading NS threshold: File not found ../Data/Thresholds99NS.dat

So I will try to link Data to a proper location. 

Now, the result plot of 
a <- a2bcovid(pat_file = pat_file)
plot_a2bcovid(a)
looked different from the example. Is this correct? 
![Screenshot 2021-06-11 at 16 52 53](https://user-images.githubusercontent.com/85743300/121707198-9e257880-cad6-11eb-80ba-3843147e95cf.png)

Hideo

**Comment by chjackson** [comment]
@himamura2 It isn't fixed yet.  Can you wait until I integrate these files properly into the R package?  I'll let you know.

**Comment by chjackson** [comment]
@himamura2 This is fixed now in the latest version, I think.   Just install the R package with `install_github("chjackson/a2bcovid")` and it should work without you having to put any extra files anywhere.   The R code for the built-in example should give results matching the [web app](https://mrc-bsu.shinyapps.io/a2bcovid/) - which are different depending on which of the four data sources are included.

**Comment by himamura2** [comment]
Thank you very much. It is working after using install_github("chjackson/a2bcovid").
